### ISSUE TITLE
feat: Rename `socials` to `connections`

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-api#106]
# Issue

Currently, we refer to the links endpoints as `socials`, but they turned out to be more than that, involving various links.

# Solution

Rename `socials` to `connections` or `links` as a generalization.

# Additional context

This may be considered a breaking change so incrementing the API version may be necessary.

**Comment by Ushie** [comment]
Has this been resolved in the feat/fly branch? or is it still up for grabs

**Comment by alexandreteles** [comment]
Still up.

**Comment by Ushie** [comment]
@ReVanced/infrastructure Maybe make a v3 milestone label/project for this repo and assign this to it?
