### ISSUE TITLE
feat: accept an array of app IDs for `app/info/` route

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-api#11]
This would allow clients to send in a single request to fetch all the metadata for the apps they need at once, instead of simultaneously sending 52 (and growing) requests

**Comment by oSumAtrIX** [comment]
Maybe via a query parameter?

?apps=pkg1,pkg2

@alexandreteles should decide on whats conventional

**Comment by Ushie** [comment]
CDN is ideal, don't we already have a CDN impl?
cc: @palmdevs

**Comment by PalmDevs** [comment]
> CDN is ideal, don't we already have a CDN impl?
> cc: @palmdevs

The one that I've implemented is just a GitHub Action wrapper for a CDN service (Web3.storage).

**Comment by alexandreteles** [comment]
> > CDN is ideal, don't we already have a CDN impl?
> > cc: @PalmDevs
> 
> The one that I've implemented is just a GitHub Action wrapper for a CDN service (Web3.storage).

Can we restart this project based on CF cache and R2? If so, please let me know. This should be easy to implement as an action for the patches repository.

**Comment by PalmDevs** [comment]
> > > CDN is ideal, don't we already have a CDN impl?
> > > cc: @PalmDevs
> > 
> > The one that I've implemented is just a GitHub Action wrapper for a CDN service (Web3.storage).
> 
> Can we restart this project based on CF cache and R2? If so, please let me know. This should be easy to implement as an action for the patches repository.
> 
> EDIT: I will design the architecture of this solution so we can revive the CDN action. It should take me a bit; I will keep this conversation open until @PalmDevs can answer.

Sure.

**Comment by alexandreteles** [comment]
Depends on: https://github.com/ReVanced/revanced-cdn-action/issues/15. I will keep this open but remove it from the milestone. The endpoint will be deactivated for the next API update until the issue is solved upstream.

**Comment by alexandreteles** [comment]
This issue is being closed after internal team deliberation, contrary to the implementation of this feature.
