### ISSUE TITLE
fix: index endpoints

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-api#14]
# Issue

The API expects clients to know about variables such as {repo}. In the example of ReVanced Manager, ReVanced Manager has to know about "revanced-patches" to fill in the variable to get the release assets for it. But ReVanced Manager should be agnostic to any repository or repository name.

# Solution

Provide index endpoints. Index endpoints list (all) possible values for variables. For example, the API `/v2/{repo}/contributors` could be changed to `/v2/contributors/{repo}` so an index page can be generated at `/v2/contributors`. The index page returns an array of {repo} objects/strings. Now, ReVanced Manager would be able to query the index page for all possible variables.

**Comment by oSumAtrIX** [comment]
How do you plan to solve the issue otherwise?

**Comment by alexandreteles** [comment]
This was solved with the implementation of:

* Support to `latest` on /patches
* Implementation of /tools and /contributors.
