### ISSUE TITLE
feat: Add new field `archived` for announcements

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-api#145]
# Issue

Scenario: Some issue leads to an announcement. Now, the issue is fixed, but the announcement is still shown to everyone. 

# Solution

Add a field `archived`. The field value may be the date the announcement has been or will be archived. The field may be nullable. If it is null, the announcement is not archived. Additionally, this field should be modifiable through a PATCH in case we want to extend or shorten the date when to archive the announcement.

**Comment by Ushie** [comment]
Maybe there's a better-fitting word than "archived"

**Comment by oSumAtrIX** [comment]
Archived is used here as a general super term. If the field is true, any consumer can handle the announcements accordingly. The website would, for example, not display them unless you also want to show archived announcements; the API can ask for a query parameter to return archived announcements and so on.
