### ISSUE TITLE
bug: Query parameters are unstable due to CloudFlare cache

### ISSUE THREAD

**Issue by kitadai31** [ReVanced/revanced-api#177]
Some endpoint like `/v2/{repo}/releases` and `/v2/{repo}/releases/latest` have query parameters, but most of the time the query parameters don't work.
Sometimes query parameter works, but then the effect of query parameter remains even I remove it.

oSumAtrIX said it's caused by CloudFlare cache. https://github.com/ReVanced/revanced-manager/pull/1785#issuecomment-2017903124

If `cf-cache-status header` response header is EXPIRED, my query parameters are working.

**Comment by oSumAtrIX** [comment]
That's not really an issue with API but more with CloudFlare configuration set up for the reason to prevent the announcement requests hitting our server. We have made some changes that will eventually allow us to change the configuration again so that query parameters work again
