### ISSUE TITLE
bug: Error 500 when request list patches

### ISSUE THREAD

**Issue by ngocdangrby** [ReVanced/revanced-api#184]
### Bug description

API returned 500 when I call request to get list of patches (https://api.revanced.app/v3/patches/latest/list)

![image](https://github.com/user-attachments/assets/73480525-743b-40e8-99e9-da423e834644)

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Not sure, but I can not reproduce this on the dev branch (https://dev-api.revanced.app)

So it must be related to some environmental configuration. Logging is not really implemented correctly, so I can not really see why it happens either: 
![image](https://github.com/user-attachments/assets/b3c00c75-bab4-43dd-be00-b061df1340f1)

In any case the dev branch should fix it.
