### ISSUE TITLE
HEAD /v3/ping always failing with 404 status code

### ISSUE THREAD

**Issue by madkarmaa** [ReVanced/revanced-api#185]
### Bug description

Executing a `HEAD` request to the route `/v3/ping` always fails with a 404 status code, even on the [docs page](https://api.revanced.app/#/API/head_v3_ping)

### Additional context

![Screenshot_2024-08-10-13-10-38-18_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/14c23495-8497-46f6-ade6-9e817fc11fa8)

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Looks to be an issue with proxy/cf
