### ISSUE TITLE
feat: improve simplicity of endpoints

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-api#39]
# About

Some endpoints are designed with the backend in mind; thus, abstraction has suffered from it, causing inconsistency in some endpoints:

A list of issues:

- Certain keywords from the GitHub backend leak to the front such as "GitHub", "Tag" or "Repository"
- Some paths were shaped the way the backend shapes them (particularly the /releases endpoint can be simplified by not referring to "tags", but instead "versions" so that "/latest" falls under a alias for the latest version)
- API Documentation mentions GitHub and Sanic implicating the backend when it should not

**Comment by alexandreteles** [comment]
Please move this to #13
