### ISSUE TITLE
feat: `/tools` replacement

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-api#48]
# Issue

Related to, but not the same as: #13
The tools endpoint currently returns an array of assets, but the format cannot easily be understood by a machine.
```json
{
  "tools": [
    {
      "repository": "revanced/revanced-patches",
      "version": "v2.186.0",
      "timestamp": "2023-07-21T15:08:47Z",
      "name": "patches.json",
      "browser_download_url": "https://github.com/ReVanced/revanced-patches/releases/download/v2.186.0/patches.json",
      "content_type": "application/json"
    },
    {
      "repository": "revanced/revanced-patches",
      "version": "v2.186.0",
      "timestamp": "2023-07-21T15:08:47Z",
      "name": "revanced-patches-2.186.0.jar",
      "browser_download_url": "https://github.com/ReVanced/revanced-patches/releases/download/v2.186.0/revanced-patches-2.186.0.jar",
      "content_type": "application/java-archive"
    },
    {
      "repository": "revanced/revanced-integrations",
      "version": "v0.114.0",
      "timestamp": "2023-07-21T15:09:05Z",
      "name": "revanced-integrations-0.114.0.apk",
      "browser_download_url": "https://github.com/ReVanced/revanced-integrations/releases/download/v0.114.0/revanced-integrations-0.114.0.apk",
      "content_type": "application/vnd.android.package-archive"
    }
  ]
}
```

Clients have to [hardcode git repository names](https://github.com/ReVanced/revanced-manager-compose/blob/e0eedf59db1051b7ae4652e2f8fb381750cae52b/app/src/main/java/app/revanced/manager/util/Constants.kt#L5-L9) and [check the file name](https://github.com/ReVanced/revanced-manager-compose/blob/e0eedf59db1051b7ae4652e2f8fb381750cae52b/app/src/main/java/app/revanced/manager/network/service/ReVancedService.kt#L33-L41) to get the asset they want or [transform the json](https://github.com/ReVanced/revanced-website/blob/34d6d07a3e0c6abfa945e1d43869ba0dbfee0399/src/data/api/index.ts#L19-L48). These things should ideally not be required to properly consume the endpoint.

# Solution

A format like this would be much easier to interpret using JSON libraries:
```json
{
     "patches": {
              "version": "v2.120.0",
              "url": "https://raw.github.com/rv-patches-v2.120.0.jar"
      },
      "integrations": {
               "version": "v12.0.0",
               "url": "https://raw.github.com/rv-integrations-v12.0.0.apk"
     },
     "patches_json": {
              "version": "v2.120.0",
              "url": "https://api.revanced.app/patches"
      },
     "manager": {
              "version": "v1.4.3",
              "url": "https://revanced.app/manager.apk"
     }
}
```
It tells you exactly which asset is which. No error-prone scanning, hardcoding or transformation needed.
This is just an example. Anything works as long as it can easily be interpreted.

**Comment by alexandreteles** [comment]
`/tools` is located in the compatibility layer, meaning it implements an older format necessary to keep current tools that use the API running without changes to their codebase (mainly the Flutter manager). There are no plans to offer a similar endpoint in the new API. If you need such an endpoint, please open a feature request issue.

Thank you.
