### ISSUE TITLE
fix: blocked origin

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-api#49]
`Access to fetch at 'https://api.revanced.app/v2/patches/latest' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by alexandreteles** [comment]
I will make the change on Cloudflare while I get things ready on the backend.

**Comment by alexandreteles** [comment]
Implemented a hotfix on Cloudflare, and will add this to the next feature pack.

**Comment by alexandreteles** [comment]
This is not a codebase issue. The headers exist in the code and are being adequately set by Sanic. This is an upstream issue, which was fixed on the CF level.
