### ISSUE TITLE
feat: `/manager` and `/patches` endpoint

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-api#50]
This was requested by @oSumAtrIX.

# `/manager` endpoint

This endpoint will return information about the latest ReVanced Manager release:
- Version
- Download link
- Amount of downloads
- Changelog of the latest release

The downloads count is used in the UI of compose manager, so it is recommended to have it if possible.
Changelog is optional and can be fetched with a second request.

# `/patches` endpoint

This endpoint will provide version and links to the latest patches and integrations.
Only needs to provide version and download link for both the assets.

**Comment by oSumAtrIX** [comment]
Can you specify in detail what the endpoints return

**Comment by Axelen123** [comment]
> Can you specify in detail what the endpoints return and behave? Also what is the motivation of this issue?

Done

**Comment by jimman2003** [comment]
Maybe for patches , we should include default-ness as a field, for OTA updating?

**Comment by oSumAtrIX** [comment]
@jimman2003 Please clarify in detail what you mean by this

**Comment by jimman2003** [comment]
Maybe for patches , we should include default-ness as a field, for OTA updating?

**Comment by Axelen123** [comment]
@jimman2003 the patches endpoint is just for versioning and has nothing to do with the existing patches endpoint or patches.json

**Comment by alexandreteles** [comment]
> This was requested by @oSumAtrIX.
> 
> # `/manager` endpoint
> This endpoint will return information about the latest ReVanced Manager release:
> 
> * Version
> * Download link
> * Amount of downloads
> * Changelog of the latest release
> 
> The downloads count is used in the UI of compose manager, so it is recommended to have it if possible. Changelog is optional and can be fetched with a second request.

`download_count` is available on the GitHub API, but as this is something somewhat challenging to emulate for other backends that might not be able to offer this information, the entity that represents a release must use an `Optional` for this type, which will require changes to the validation layer as well.

This should be reasonably easy to implement, whether at the router level or as a class method, as all it has to do is consume the methods that generate releases.

> # `/patches` endpoint
> This endpoint will provide version and links to the latest patches and integrations. Only needs to provide version and download link for both the assets.

This nomenclature has to change. `/v2/patches` already exists and uses the default format for the `patches.json` file. If all you need is an endpoint that returns version and download links, this will be better implemented inside the `/manager` endpoint to keep consistent semantics. The endpoint could return something like:

```json
{
  "data": {
    "manager": {
      "version": 123,
      "body": "I am going insane....",
      "assets": [
        {
         "filename": "manager.apk",
         "download_url": "https://guh.husk",
         "download_count": 2123
        }
      ]
  },
  "patches": {
      "version": 321,
      "body": "I am going insane....",
      "assets": [
        {
         "filename": "patches.jar",
         "download_url": "https://guh.husk",
         "download_count": 3212
        },
        {
         "filename": "patches.dex",
         "download_url": "https://guh.husk",
         "download_count": 2312
        }
      ]
    }
  }
}
```

**Comment by oSumAtrIX** [comment]
> will be better implemented inside the /manager endpoint

The patches have nothing to do with ReVanced Manager, I don't think that this is a good idea.

**Comment by TheAabedKhan** [comment]
>Changelog of the latest release

If we just get the latest changelog of the manager, then we can't show the unseen changelogs like the Flutter Manager.

>version and links to the latest patches and integrations

This way, the users are forced to use the latest patches. We should allow them to decide whether to update or not by showing the patches changelog.

**Comment by alexandreteles** [comment]
> > will be better implemented inside the /manager endpoint
> 
> The patches have nothing to do with ReVanced Manager, I don't think that this is a good idea.

There is already another endpoint dedicated to patches and their metadata. The `/v2/manager` endpoint is just a way to give the manager people the data they need in order to instrumentalize the application. `/v2/patches` already exists so we would be required to change its data format and change clients already using it (website).

**Comment by oSumAtrIX** [comment]
> There is already another endpoint dedicated to patches and their metadata

Which one? I can not find `/v2/patches`.

**Comment by Ushie** [comment]
Which one? I can not find /v2/patches.

https://api.revanced.app/v2/patches/latest

**Comment by alexandreteles** [comment]
Is this somehow related to: https://github.com/ReVanced/revanced-manager/issues/572?

**Comment by Ushie** [comment]
It looks like it, for the /patches endpoint the structure is essentially the same and I don't see any other motivation except that

But for the /manager endpoint, I don't particularly see the reason for that, we have /v2/releases/repo which is that and better, is that just motivated by the lack of knowledge of the repo name?

**Comment by oSumAtrIX** [comment]
Some motivations that support this issue:

- API consumers can't know the repo name and need to hardcode it
- The resolution of the generalization of those endpoints as "repositories" like it is now, prevents adding specialized fields to the endpoints that would allow for seamless scaling in the future if necessary
