### ISSUE TITLE
feat: index endpoint

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-api#68]
# Issue

Currently, the API does not offer an index API endpoint. This lack prevents publishing metadata about the current API owner, such as E-Mail/ Contact info, name & description, etc.

This issue has been found when making the ReVanced website consume the API to display contact information in the footer. Due to the lack of this API, the following sections can not be displayed and would otherwise have to be hardcoded:

![image](https://github.com/ReVanced/revanced-api/assets/13122796/c357db1b-62cf-4507-b554-a75c97e8ef0d)

# Solution

Offer an index API endpoint. It could return something like this:

```json
{
 "name": "ReVanced",
 "about": "long description"
 "contact": [
   { "method": "mail", "value": "some@mail.com" }
 ]
}
```

# Additional context

This API may clash semantically with the links and donations API endpoints. Restructuring/ Merging endpoints may be favourable.

**Comment by Ushie** [comment]
@alexandreteles I can work on this, where should the endpoint be?

**Comment by alexandreteles** [comment]
> @alexandreteles I can work on this, where should the endpoint be?

This could be on `/v2/info` as the website exclusively uses the information. `/v2/index` sounds like a general index of API endpoints already provided by the API root path and the OpenAPI spec.

Would it be fine if we collapsed the other two `info` related endpoints in this single one following this format, so we have compatibility with JS objects:

```json
{
	"info": {
		"name": "ReVanced",
		"about": "long description",
		"contact": [
			{
				"method": "mail",
				"value": "some@mail.com" 
			},
		],
		"socials": [
			{
				"name": "string",
				"url": "string"
    		},
  		],
		"donations": {
			"wallets": [
				{
					"network": "string",
					"currency_code": "string",
					"address": "string",
					"preferred": true
				}
			],
		    "links": [
				{
					"name": "string",
					"url": "string",
					"preferred": true
				}
			]
		},
	}
}
```
