### ISSUE TITLE
feat: first party API clients

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-api#75]
# Issue

Currently, the API documents itself but does not provide first-party API clients.  This requires every API consumer to develop their own client.

# Solution

Release API clients for any language, such as JS or Kotlin.

# Motivation

The API clients will act as first-party libraries with few breaking changes. This would allow API consumers to consume the API even if the API introduces breaking changes because the API client would be adjusted accordingly to support the new API with fewer or no breaking changes to the public API it provides.

# Additional context

It may be necessary to refactor this repository structure so that a dedicated directory can be reserved to host the clients.

**Comment by alexandreteles** [comment]
Clients are better served from their repository: `revanced-api-python`, `revanced-api-kotlin`, or a central `revanced-api-clients` so their development can be compartimentalized appropriately. I do not foresee this being worked on any time soon unless either the Website or Manager team takes time to fork their implementations into libraries.

**Comment by Ushie** [comment]
I may be interested in a JS/TS client, just for the sake of learning
