### ISSUE TITLE
feat: return org-wide contributors

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-api#9]
There is currently only a way to get the contributors of a specific repository, instead of all repositories org-wide 

![image](https://github.com/revanced/revanced-api/assets/79272171/824c2150-5796-4c31-855d-9216bc6dfc08)

This means that everytime a user would enter a contributors page like revanced.app/contributors or in ReVanced Manager, there would be a request for each repository (which would be like 8 requests per user at the moment)

**Comment by oSumAtrIX** [comment]
I'd propose:

/contributors to return all (array of repos)
/contributors/{repo} to return for a specific repo

**Comment by Ushie** [comment]
This also is necessary for it to be completely dynamic on the client side, as to request a repository specific request that implies awareness of the repository and hardcoding it

**Comment by alexandreteles** [comment]
> I am not sure what internal abstraction change, but as of now, an API client has to make X requests if there is X repos. If /contributors returns all repos with all their contributors, X requests would be turned into 1 request. Clients that don't request all contributors can request via the /contributors/{repo} endpoint to for example reduce bandwidth or when they don't need all repos at a time

This goes back to what I said:

> A possible solution to the request problem would be to rebuild the old /contributors endpoint on top of the current API abstraction (which would put it in the compatibility layer).

And we keep the current `/{repo}/contributors` endpoint untouched. As for this:

> This also is necessary for it to be completely dynamic on the client side, as to request a repository specific request that implies awareness of the repository and hardcoding it

It will be hardcoded *somewhere* unless we list *all* repositories under our organization for the GitHub backend. I'm fine with doing so on the API side. As I previously mentioned, this would be built as an endpoint in the compatibility layer (meaning that backends implementing this Protocol wouldn't be required to implement this method).

**Comment by oSumAtrIX** [comment]
I am not questioning how you implement it; you are free to however you think is suitable. Moving to #14.

**Comment by xafn** [comment]
To solve the issue of multiple requests and overloading the server, what if we used batch requests to fetch all the repos we want in the body of one HTTP request?

**Comment by alexandreteles** [comment]
> To solve the issue of multiple requests and overloading the server, what if we used batch requests to fetch all the repos we want in the body of one HTTP request?

This would be better done by using something like GraphQL, but it doesn't necessarily equal to lower server load. Prisma recently moved from GraphQL to a JSON-based backend for performance reasons: https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t

We need to run tests to check which solution is faster and which solution results in a higher/lower server load. But I don't expect the increase in the number of requests to be significantly impactful.
