### ISSUE TITLE
feat: return brand logo in `/info` endpoint

### ISSUE THREAD

**Issue by BenjaminHalko** [ReVanced/revanced-api#92]
This endpoint will return brand links for ReVanced.

**Comment by Ushie** [comment]
Can you clarify what "brand links" are? please show an example response

**Comment by Ushie** [comment]
Can you clarify what "brand links" are? please show an example response

**Comment by oSumAtrIX** [comment]
@Ushie  

RE: https://github.com/ReVanced/revanced-manager/pull/1294#discussion_r1341624199

**Comment by Ushie** [comment]
It would be better if you provided an example response, I'm not sure how you exactly want the ReVanced "branding" to be returned, what would it be used for, and why it belongs in the API. And if for whatever reason it is considered, what would you provide? there's no single correct variant of the logo

**Comment by alexandreteles** [comment]
Looking into https://github.com/ReVanced/revanced-manager/pull/1294#discussion_r1341624199 I'm not entirely sure of which information the endpoint `/v2/info` is expected to return. This seems to be a simple change, would you care to provide an example response that includes the changes you want to see implemented?

**Comment by oSumAtrIX** [comment]
I'd say the info endpoint would have a `branding` object field with a field `logo` with a link to the logo being the value. In our specific case, the question would be where we would host the file. Lets wait for @BenjaminHalko.

**Comment by BenjaminHalko** [comment]
I thought the API would just return what is in the revanced branding repo

**Comment by oSumAtrIX** [comment]
How would that work internally?

**Comment by BenjaminHalko** [comment]
I assumed it would just return something like this:
`logo`: https://github.com/ReVanced/revanced-branding/raw/main/assets/revanced-logo/revanced-logo.svg
`horizontal-dark`: https://github.com/ReVanced/revanced-branding/raw/main/assets/revanced-headline/revanced-headline-horizontal-dark.svg
`horizontal-light`: https://github.com/ReVanced/revanced-branding/raw/main/assets/revanced-headline/revanced-headline-horizontal-light.svg
`vertical-dark`: https://github.com/ReVanced/revanced-branding/raw/main/assets/revanced-headline/revanced-headline-vertical-dark.svg
`vertical-light`: https://github.com/ReVanced/revanced-branding/raw/main/assets/revanced-headline/revanced-headline-vertical-light.svg
